apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-config
  namespace: otel
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://elastic-apm-server.elastic-system.svc.cluster.local:8200"
  OTEL_SERVICE_NAME: "javaapp"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapp
  namespace: otel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javaapp
  template:
    metadata:
      labels:
        app: javaapp
    spec:
      containers:
      - name: javaapp
        image: vmisra1989/javaapp:1.0
        envFrom:
        - configMapRef:
            name: otel-config
        ports:
        - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: javaapp
  namespace: otel
spec:
  selector:
    app: javaapp
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
  type: ClusterIP
